name: Vulcan-Anti
version: 1.0.0
main: AntiCheat\ACLoader
api: 5.0.0
author: Froz
description: similar a java de vulcan paid

permissions:
  ac.alert:
    description: "Permite recibir alertas de detecciones de hacks"
    default: op
  ac.bypass:
    description: "Permite evitar las detecciones del anti cheat"
    default: op
